//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workoutplanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class back
    {
        public int workout_num { get; set; }
        public string workout_name { get; set; }
        public string sets_num { get; set; }
        public int intensity_num { get; set; }
        public Nullable<System.DateTime> addeddate { get; set; }
    }
}
