//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workoutplanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_num { get; set; }
        public System.DateTime birth_date { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public System.DateTime starting_date { get; set; }
    }
}
